{% set version = "1.16.1" %}

package:
  name: netavark
  version: {{ version }}

source:
  url: https://github.com/containers/netavark/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e655fcd882fe891bcc8328ddcfff3745831c8b1013ae59f012d37ce87175b0b3

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - libprotobuf

test:
  commands:
    - $PREFIX/lib/podman/netavark --help

about:
  home: https://github.com/containers/netavark
  license: Apache-2.0
  license_family: Apache
  summary: Netavark is a rust based network stack for containers.
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - conda-forge/podman
