{% set version = "1.15.2" %}

package:
  name: netavark
  version: {{ version }}

source:
  url: https://github.com/containers/netavark/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 84325e03aa0a2818aef9fb57b62cda8e9472584744d91ce5e5b191098f9e6d6a

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - libprotobuf

test:
  commands:
    - $PREFIX/lib/podman/netavark --help

about:
  home: https://github.com/containers/netavark
  license: Apache-2.0
  license_family: Apache
  summary: Netavark is a rust based network stack for containers.
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - conda-forge/podman
